apiVersion: apps/v1
kind: Deployment
metadata:
  name: myApp
spec:
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
    spec:
      containers:
      - image: nginx:1.7.9
        name: myApp
        volumeMounts:
        - mountPath: /etc/extra
          name: extra-volume
        - mountPath: /usr/share/nginx/html
          name: myApp
      volumes:
      - name: extra-volume
        secret:
          secretName: test-secret
      - emptyDir: {}
        name: myApp
